# Data Manipulation with Pandas and Numphy.

used for data manipulation-->Data manipulation is the process of changing, organizing or transferring data to make it useful, readab le or suitable for analysis. It involves tasks like cleaning, filtering, sorting, grouping or calculating new values from existing data.

Tools like Pandas and Numpy, popular python libraries are often used to streamline these tasks. Pandas excels at handling structured data, like tables of crypto trades, for filtering or grouping, while numphy supports fast numerical computations such as calculating average pricess or returns

For instance, a crypto investor might manipulate data by filtering trades to show only Bitcoin transactions over $5000 sorting them by time stamp to track price movements and aggregating daily totals to assess volume. This helps uncover trends optiize strategies and ensure data accuracy, utimately supporting better decisions in the fast paced crypto market.

# Pandas
Pandas is a popular pytyhon library used for working with data. It helps you load, clean, analyse and manipulate data easily. Think of it like an Excel spread sheet in python. It is great for handling tables of data

# Key concepts

Series

A single column of data(like a list with labels)

Indexes: labels for rows, helping you identify and access data. You can load data from files(csv, Excel etc), manipulate it and save it back.

# Installing /Importing Pandas
There are a number of installation options for example:

1 pip install pandas-->goes to Python environment not base environment to manage dependencies.

2 Going outside and creating a file called, requirements.txt. This file is going to help us sieve and store my dependencies such that anyone else that would want to use my code follows through well without being disturbed.
 
After opening the requirements.txt file; inside it write pandas then go ahead and proceed to the terminal and in put:pip intall-r requirements.txt to activate and have pandas installed.

pip freeze>requirements.txt input in the terminal enables one to add more dependencies in the requirements.txt file in case one forgot to include them earlier or the ones already in the file dont meet the versions an individual prefers to use. It also displays all dependencies with in the requirements.txt file.


In [1]:
# working with pandas.

import pandas as pd

# Creating a DataFrame
A data frame is like a table with rows and columns. Lets create one with sample crypto data i.e (coin name, price,trade volume).

In [7]:
# Creating a dictionary with crypto data(dict of list)
data={
    'coin':['Bitcoin','Ethereum','Ripple','Litecoin'],
    'price':[45000,3000,0.85,120],
    'volume':[15000,'nan',200000,50000]
}
df=pd.DataFrame(data) # pd is a module, DataFrame is a class/function(from a module we can alwas get a function or class),
print(df)              # depending on how a module is structured--> DataFrame is a class in pd.

       coin     price  volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00     nan
2    Ripple      0.85  200000
3  Litecoin    120.00   50000


#### Exploring data

In [8]:
df

coin     price  volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00     nan
2    Ripple      0.85  200000
3  Litecoin    120.00   50000

In [9]:
print(df.head(2))   # prints out the first two rows

       coin    price volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0    nan


In [10]:
print(df.tail(2))   # prints the last two rows

       coin   price  volume
2    Ripple    0.85  200000
3  Litecoin  120.00   50000


In [11]:
df.head(2) # .head fetches a specific number of rows at the top of the table.

coin    price volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0    nan

#### Getting information(investigation)

In [ ]:
# volume for Ethereum is missing
print(df.info())    # gives information if you have empty rows or not. Object--> also identified as string.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   coin    4 non-null      object 
 1   price   4 non-null      float64
 2   volume  4 non-null      object 
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes
None


## Basic Data Manipulation

In [ ]:
# select specific columns
print(df[['coin', 'price']])    # when you select more than one column, it becomes a list, need to use sq brackets



       coin     price
0   Bitcoin  45000.00
1  Ethereum   3000.00
2    Ripple      0.85
3  Litecoin    120.00


### Filter Rows

In [ ]:
# want to get the price thats greater than 100
print(df[df['price']>100])  # filtered out all prices that are greater than 100

       coin    price volume
0   Bitcoin  45000.0  15000
1  Ethereum   3000.0    nan
3  Litecoin    120.0  50000


### Sorting Data
Sort by column like price in ascending order/descending order

In [ ]:
# Asceding order
print(df.sort_values('price'))  # sorts prices in ascending order from the lowest to the highest.

       coin     price  volume
2    Ripple      0.85  200000
3  Litecoin    120.00   50000
1  Ethereum   3000.00     nan
0   Bitcoin  45000.00   15000


In [ ]:
# Descending order
print(df.sort_values('price', ascending=False)) # sorts values in descending order form the highest to the lowest.

       coin     price  volume
0   Bitcoin  45000.00   15000
1  Ethereum   3000.00     nan
3  Litecoin    120.00   50000
2    Ripple      0.85  200000


### Add new column
Creating a new column--> price after 2% change

In [ ]:
df['price_after_2pct']=df['price']*1.02
print(df)   # gives us data in 4 columns.

       coin     price  volume  price_after_2pct
0   Bitcoin  45000.00   15000         45900.000
1  Ethereum   3000.00     nan          3060.000
2    Ripple      0.85  200000             0.867
3  Litecoin    120.00   50000           122.400


In [ ]:
df.describe()   # gives us statistical metrics of the the DataFrame(what) but this only works with numeric data

price  price_after_2pct
count      4.000000          4.000000
mean   12030.212500      12270.816750
std    22023.550649      22464.021662
min        0.850000          0.867000
25%       90.212500         92.016750
50%     1560.000000       1591.200000
75%    13500.000000      13770.000000
max    45000.000000      45900.000000

# Save and load data with Pandas.

In [ ]:
# 
df.to_csv('', index=False)

In [ ]:
# 
df.to_csv('crypto_data.csv', index=False)

# Numpy

Numpy is a powerful Python library for numerical computations, especially useful for working with arrays(lists)of numbers and performing mathematical operations. Its a foundation for data manipulation, often used alongiside Pandas, and is great for tasks like calculations and handling crypto related data. Below are the basic steps for installing Numpy, creating arrays and performing common operations with simple code.

#### Installing and Importing Numpy

In [20]:
# 
import numpy as np

### Creating a Numpy Array
A numpy array is like a list b ut optimized for Maths and faster operations. Lats create arrays with simple crypto data i.e (coins, prices, volume)

In [21]:
#
prices=np.array([45000, 50000, 40000, 20000])
print(prices)

[45000 50000 40000 20000]


In [ ]:
#
print(prices.shape) # fetches the number of elements in the array prices.

(4,)


## Data Types

In [ ]:
print(prices.dtype) # Fetches the data type in the array prices

int64


### Basic Data Manipulation

In [40]:
# Adding 1000 to all prices
prices=np.array([45000, 50000, 40000, 20000])
prices_plus_100=prices+1000
print(prices_plus_100)

[46000 51000 41000 21000]


In [41]:
# Compute for 2% increase in price
price_s=np.array([46000, 51000, 41000, 21000])
price_increase=prices+1.02
print(price_increase)

[45001.02 50001.02 40001.02 20001.02]


In [43]:
# Filter data

higher_price=price_s[price_s> 20000]
print(higher_price)

[46000 51000 41000 21000]


## Basic Statistical Functions

In [ ]:
volume=np.array([500000, 300000, 200000, 100000])
print("\nStatistics for volume:")
print('mean(Average):', np.mean(volume))            # Average volume
print("minimum:",np.min(volume))                    # Minimum volume
print("maximum:",np.max(volume))                    # Maximum volume
print("sum:", np.sum(volume))                       # Total sum of volumes
print("standard Dev(volatility):", np.std(volume))  # Standard Deviating Volatility


Statistics for volume:
mean(Average): 275000.0
minimum: 100000
maximum: 500000
sum: 1100000
standard Dev(volatility): 147901.9945774904


## Working with 2D Arrays
Numpy can handle multi demensional arrays. Lets combine our data into a 2D array.

In [46]:
# 2D Array
crypto_data=np.array([
    [45000,5000],
    [30000,28000],
    [11988,8943]
])

print(crypto_data)

[[45000  5000]
 [30000 28000]
 [11988  8943]]


In [ ]:
# Access row
crypto_data[2]  # we use indexes to check for the data that we want from our data.

array([11988,  8943])

In [ ]:
# Access column
crypto_data[:,1]    # helps us access a column of our data.

array([ 5000, 28000,  8943])